- hosts: localhost
  vars:
    jenkins_hostname: localhost
  roles:
    - role: elasticsearch
    - role: java
    - role: mongodb
      become: true
    - role: gravitee
      become: true
    - role: k8s
      become: true
    - role: docker
      become: true
